fixed bugs and added API call
codenteq/e-exam pull request #49
Opened 2022-11-09 18:44 UTC by ahmetarsiv

- While testing Lesson, I got an unresolved error in the show function, for now, I've added TODO to the comment line, but I'm waiting for support for this.

- Fixed a few bugs and path fixes.

2022-11-10 17:05 UTC, karabayyazilim requested changes

2022-11-10 17:05 UTC, karabayyazilim commented on backend/app/Http/Controllers/API/Manager/Lesson/LessonController.php
> +        return $this->successResponse(new LessonResource($this->lessonService->show($lesson, ['company_id' => Helper::userInfo()->company_id])));
You should change it like this

`$this->lessonService->show($lesson, ['lesson'], ['company_id' => Helper::userInfo()->company_id]);`

2022-11-10 17:21 UTC, ahmetarsiv commented on backend/app/Http/Controllers/API/Manager/Lesson/LessonController.php
> +        return $this->successResponse(new LessonResource($this->lessonService->show($lesson, ['company_id' => Helper::userInfo()->company_id])));
The changes are working in the base, I'm pulling again

2022-11-10 17:25 UTC, ahmetarsiv commented
Todo deleted and the comment line has been removed.

2022-11-11 07:06 UTC, karabayyazilim approved these changes

2022-11-11 07:07 UTC, merged